//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeedInvoices.Service.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SpeedInvoicesEntities : DbContext
    {
        public SpeedInvoicesEntities()
            : base("name=SpeedInvoicesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Etat> Etats { get; set; }
        public virtual DbSet<Facture> Factures { get; set; }
        public virtual DbSet<Prestation> Prestations { get; set; }
        public virtual DbSet<Structure> Structures { get; set; }
    }
}
